### PR TITLE
[DS-254] Feat/px to rem

### PR DESCRIPTION
**Pull request by Christos-Zacharopoulos**
## Description

Change all occurrences of px to rem. This will allow proper scaling on screens larger than 1920.

Resolves https://github.com/Orfium/orfium-ictinus/issues/368 
ticket: https://orfium.atlassian.net/browse/DS-254

## Test Plan

Update all snapshots.

### CODE REVIEW

**Comment by whosyourtaco** [comment]
Candidates for changing:

- `PositionInScreen.style.tsx`, line 23,24
- `Label.style.ts`, line 6
- `BarChart/CustomTooltip.style.ts`, line 29, 30
- `LineChart.tsx`, line 66, 67
- `LineChart/CustomTooltip.style.ts`, line 39
- `MonthWrapper.style.ts`, line 22
- `Spinner.style.tsx` line 10, 11
- `TextInputBase.style.ts` line 128
- `TopAppBar/Logo.style.ts` line 11
- `Search.style.ts` line 16

**Comment by Christos-Zacharopoulos** [comment]
> Candidates for changing:

> * `PositionInScreen.style.tsx`, line 23,24 
 This should remain in px as it calculates the fixed position of an item according to size screen width and height as well as the position of it's parent.
> * `Label.style.ts`, line 6
 This is a const. Wherever it's used it's wrapped in rem. Changed it to be exported as an rem.
> * `BarChart/CustomTooltip.style.ts`, line 29, 30
 Fixed
> * `LineChart.tsx`, line 66, 67
 Fixed
>  * `LineChart/CustomTooltip.style.ts`, line 39
 Fixed
>  * `MonthWrapper.style.ts`, line 22
  Fixed
>  * `Spinner.style.tsx` line 10, 11
 Fixed
>  * `TextInputBase.style.ts` line 128
 Fixed
>  * `TopAppBar/Logo.style.ts` line 11
 Fixed
>  * `Search.style.ts` line 16
 Fixed

**Review by panvourtsis — COMMENTED** [review]
One consideration here, i want this to be abstract so we can define the base globally.

Right now the base is "16px" check [here](https://polished.js.org/docs/#rem).
`Convert pixel value to rems. The default base value is 16px, but can be changed by passing a second argument to the function.`

I would recommend doing a function rem to have a global base

```
const rem = (px: number | string) => polishedRem(px, typography.globalFontSize);
```

**Comment by Christos-Zacharopoulos** [comment]
> One consideration here, i want this to be abstract so we can define the base globally.
> 
> Right now the base is "16px" check [here](https://polished.js.org/docs/#rem). `Convert pixel value to rems. The default base value is 16px, but can be changed by passing a second argument to the function.`
> 
> I would recommend doing a function rem to have a global base
> 
> ```
> const rem = (px: number | string) => polishedRem(px, typography.globalFontSize);
> ```

I agree to the idea of abstracting the 'rem' function but since rem() returns rem ( duuuh ) then I find it hard understanding what is the value of passing rem a base. The base value of rem is the font-size of root and not it's parent. It would be more useful if it was returning em.

**Review by panvourtsis — APPROVED** [review]

**Review by whosyourtaco — APPROVED** [review]

**Pull request merged**
