### PR TITLE
[FE-26] [DEVOPS-800] Feat/ Disable Dependabot Review Apps 

### PR DESCRIPTION
**Pull request by Christos-Zacharopoulos**
## Description

In this PR we add a check if the pr contains the label dependencies, then we mustn't create a Review App and we shouldn't delete as well

tickets:
[orfium.atlassian.net/browse/FE-26](https://orfium.atlassian.net/browse/FE-26)
[orfium.atlassian.net/browse/DEVOPS-800](https://orfium.atlassian.net/browse/DEVOPS-800)

### CODE REVIEW

**Comment by panvourtsis** [comment]
@TDaglis i feel we are ok in this to put the role of was publicly don't you think so?

**Comment by panvourtsis** [comment]
@TDaglis reminder

**Comment by panvourtsis** [comment]
@Christos-Zacharopoulos is this still valid ?

**Comment by Christos-Zacharopoulos** [comment]
@panvourtsis If we are ok with the Teardown Review Token being here yes.

**Review by panvourtsis — APPROVED** [review]

**Pull request merged**
