### PR TITLE
feat: select with final form debugging [WIP]

### PR DESCRIPTION
**Pull request by kostasdano**
## Description

This is a **WIP PR** to investigate the Select - ReactFinalForm integration bug

### CODE REVIEW

**Comment by whosyourtaco** [comment]
Proposal of a different solution:

Revert Select to its original state, without any changes.

Add 
```        
onMouseDown={event => {
   event.preventDefault();
}}
``` on the ListItem component.

This will effectively prevent the onBlur method from running `onMouseDown` (it blurs by default) and will let `onClick` run (since in this case the onBlur event blocks the onClick event). The blur event will still happen, but only after `onClick` is finished.

**Comment by kostasdano** [comment]
> Proposal of a different solution:
> 
> Revert Select to its original state, without any changes.
> 
> Add
> 
> ```
> onMouseDown={event => {
>    event.preventDefault();
> }}
> ```
> 
> on the ListItem component.
> 
> This will effectively prevent the onBlur method from running `onMouseDown` (it blurs by default) and will let `onClick` run (since in this case the onBlur event blocks the onClick event). The blur event will still happen, but only after `onClick` is finished.

nice approach! this actually works and it also prevents the awkward animation where the textfield label falls and then elevates back when an option is clicked

**Review by Christos-Zacharopoulos — APPROVED** [review]
After fiddling around with it, I couldn't find any reason not to go with @whosyourtaco proposal. 

Maybe add a github issue referencing this PR in order to revisit this in the future.

**Comment by kostasdano** [comment]
Closing this PR in order to open a new one on a different branch and only with the ListItem.tsx change

**Pull request closed without merging**
