### PR TITLE
feat(banner): add alternative cta / button

### PR DESCRIPTION
**Pull request by tsevdos**
## Description

[Ticket](https://orfium.atlassian.net/browse/NDS-901)

### CODE REVIEW

**Review by kostasdano — CHANGES_REQUESTED** [review]
~`NotificationActions` type includes `secondaryCTALabel` and `secondaryCTA`.  You should use these instead of adding alternativeCTA. Check `Toast` or `Snackbar` Notifications for reference~

**Comment by tsevdos** [comment]
Hello @kostasdano

I started the implementation as you state (with primary and secondary),  but after communicating with @panvourtsis we decided to go with the "alternative" name approach. Can you have a chat with him to be all on the same page. For me it is the exact same thing (minor change/fix).

best regards,
John

**Comment by panvourtsis** [comment]
I  just have communicated with Kostas regarding this and he is now up to speed with the situation. Thanks!

**Review by kostasdano — APPROVED** [review]
at first I didn't understand the direction of the implementation but now we are at the same page, nice work!

**Pull request merged**
