### PR TITLE
[No-Jira] Feat/select area width fix

### PR DESCRIPTION
**Pull request by Christos-Zacharopoulos**
## Description

This PR resolves a minor issue on DS on sizing of outlined TextField.

The outlined TextField has it's border visually created by a box-shadow. This results that the width of the component is larger than the width that the DOM gives to the component.

No ticket exists for this. If we consider it useful , I will create one to pass this for Design QA.

## Screenshot

Before the proposed change
before

with the proposed change
after

## Test Plan

Updated snapshots

### CODE REVIEW

**Comment by panvourtsis** [comment]
The solution seems a bit laggy isn't it?

**New one**
ezgif com-gif-maker (5)

**Old one**
ezgif com-gif-maker (6)

**Comment by Christos-Zacharopoulos** [comment]
> The solution seems a bit laggy isn't it?
> 
> **New one**
> ezgif com-gif-maker (5)
> 
> **Old one**
> ezgif com-gif-maker (6)

Yea it actually seems very laggy watching them like this next to each other.  I'll try to figure out something later since this is not an immediate request. Feel free to pitch any ideas that could help.

**Comment by panvourtsis** [comment]
any news heres?

**Comment by mkarajohn** [comment]
Have you tried making it an inset shadow instead of a border? May help with the perceived lagginess

**Comment by Christos-Zacharopoulos** [comment]
> any news here?

have not had the time to check this again.

**Comment by Christos-Zacharopoulos** [comment]
> Have you tried making it an inset shadow instead of a border? May help with the perceived lagginess

This was the previous implementation I think , but it was messing up the spacings in the design team , since shadow is outside the space a component takes in the DOM.

**Comment by mkarajohn** [comment]
> > Have you tried making it an inset shadow instead of a border? May help with the perceived lagginess
> 
> This was the previous implementation I think , but it was messing up the spacings in the design team , since shadow is outside the space a component takes in the DOM.

From what I can see in the diff, it was not an inset shadow :eyes:

**Comment by panvourtsis** [comment]
closing this for now as there isn't something new

**Pull request closed without merging**
