### PR TITLE
fix(typescript): fixed typescript errors for button

### PR DESCRIPTION
**Pull request by elektracodes**
## Description
Fixed typescript errors on button

### CODE REVIEW

**Review by kostasdano — APPROVED** [review]
🎉 🚀

**Review by panvourtsis — APPROVED** [review]

**Comment by panvourtsis** [comment]
please check as well that the button can take HTML button props without a problem before merge

**Comment by elektracodes** [comment]
@panvourtsis It does. We checked it in Portal.

**Comment by whosyourtaco** [comment]
Please wait a bit, checking a different implementation with @panvourtsis. Will update here

**Comment by whosyourtaco** [comment]
> Please wait a bit, checking a different implementation with @panvourtsis. Will update here

@kostasdano @elektracodes @panvourtsis Please check this PR for a proposed solution that follows the same logic we've used for the TextField component. [PR](https://github.com/Orfium/orfium-ictinus/pull/362)

**Pull request closed without merging**
