### PR TITLE
[DS-286]: feat(assetmatching): component deleted

### PR DESCRIPTION
**Pull request by SVonKarajann**
## Description

[Ticket](https://orfium.atlassian.net/browse/DS-286)

### CODE REVIEW

**Review by Christos-Zacharopoulos — APPROVED** [review]

**Comment by panvourtsis** [comment]
we should wait for @whosyourtaco to take the component to use it on his product

**Review by panvourtsis — CHANGES_REQUESTED** [review]
@whosyourtaco

**Comment by whosyourtaco** [comment]
> waiting on @whosyourtaco to take the component on his product

Have a task ready for this, will update here when it's done!

**Comment by mkarajohn** [comment]
image
image

**Comment by panvourtsis** [comment]
@whosyourtaco lets us know here as this is still pending and idle

**Comment by whosyourtaco** [comment]
> @whosyourtaco let us know here as this is still pending and idle

You can now safely remove this component! The extraction is complete.

**Comment by Christos-Zacharopoulos** [comment]
> > @whosyourtaco let us know here as this is still pending and idle
> 
> You can now safely remove this component! The extraction is complete.

image

**Review by panvourtsis — APPROVED** [review]

**Pull request merged**
