### PR TITLE
refactor/issue 59

### PR DESCRIPTION
**Pull request by michalisKout**
## Description

This PR introduces a refactor of the checkbox component and adds its related unit tests.

Before the current implementation, the inner state of the component was not used to change its `checked` attribute. Only a parent component was able to change the `checked` attribute of the input element. 
The main issue was that a user was not able to change the checkbox's value in the related storybook's showcase tab.

That said, this PR changes the way checkbox handles the `checked` prop in combination with its `isChecked` state.

## Screenshot

checkbox-change-values

## Test Plan

Test Scenarios: 
- Tests that component successfully changes its state. 

> _By clicking on a checkbox we can change its `checked` attribute (true or false)._

- Tests that the onClick function is successfully invoked. 

>  _By clicking on a checkbox we can use the onClick function._

- Tests that disabled attribute is working properly. 

> _By clicking on a disabled checkbox we cannot use the onClick function._

### CODE REVIEW

**Comment by michalisKout** [comment]
**Status Update**:  Currently this PR is frozen due to conflicts between snapshot and unit tests. I will convert this PR to `Draft` until we find a proper solution.

**Review by panvourtsis — APPROVED** [review]

**Review by panvourtsis — CHANGES_REQUESTED** [review]
please change this to v2 branch

**Comment by michalisKout** [comment]
> please change this to v2 branch

done

**Review by panvourtsis — APPROVED** [review]

**Comment by panvourtsis** [comment]
resolve issues and merge here

**Comment by panvourtsis** [comment]
image
credits goes to @Christos-Zacharopoulos

**Comment by panvourtsis** [comment]
image

**Pull request merged**
